# ===============================
# alpha_CRY_onspill-LH_au.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.root"

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 41100000000
    livetime: 10680000

output:
    out_path: "../output/results/alpha_CRY_onspill-LH_au"