# =============
# alpha_test.yaml
#
# Test pipeline with one file
# =============

process:
    # file_name: "nts.mu2e.CosmicCRYSignalAllOffSpillTriggered-LH.MDC2020as_best_v1_3_v06_03_00.001202_00050440.root"
    file_name: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/files/nts.mu2e.CosmicCRYSignalAllOffSpillTriggered-LH.MDC2020as_best_v1_3_v06_03_00.001202_00050440.root"
    use_remote: false
    verbosity: 2
    worker_verbosity: 1
    cutset_name: "alpha"

postprocess:
    write_events: true
    generated_events: 4895

output:
    out_path: "../output/results/alpha_test"