# ===============================
# alpha_CRY_offspill-LH_aq.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aq_best_v1_3_v06_03_00.root"
    location: "tape"

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 41100000000
    livetime: 10690000

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/alpha_CRY_onspill-LH_aq"