# ===============================
# alpha_signal_onspill-LH_aq.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020aq_best_v1_3_v06_03_00.root"
    location: "tape"
    cuts_to_toggle:
        unvetoed: false

postprocess:
    write_events: false
    write_event_info: false
    generated_events: 4000000
    livetime: null

output:
    out_path: "../output/results/alpha_signal_onspill-LH_aq"