# ===============================
# alpha_signal_onspill-LH_aw.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020aw_best_v1_3_v06_05_00.root"
    on_spill: true
    location: "disk"
    cutset_name: "alpha"
    cuts_to_toggle:
        unvetoed: false

postprocess:
    write_events: false
    write_event_info: false

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/alpha_signal_onspill-LH_aw"