# Run multiprocessing on small remote file list with high verbosity

process:
    file_list_path: "../input/file_lists/nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.10.txt"
    on_spill: true
    cutset_name: "alpha"
    max_workers: 10
    use_remote: true
    use_processes: true
    verbosity: 2
    worker_verbosity: 2
    location: "disk"

postprocess:
    generated_events: 48721
    write_events: true
    write_event_info: false

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/debug"