# ===============================
# example.yaml
# ===============================

process:
    file_name: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/files/nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.001202_00010066.root"
    cutset_name: "SU2020b"
    use_remote: false
    max_workers: 1

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 50000000
    livetime: 13019.4

output:
    out_path: "../output/results/example"