#
# preselection_CRY_onspill-LH_au.yaml
#


process:
    file_list_path: "../input/file_lists/nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.100.txt"
    on_spill: true
    cutset_name: "SU2020a" 
    groups_to_toggle:
        Tracker : false
        CRV : false
        Momentum: false
    max_workers: 100 
    verbosity: 1 

postprocess:
    write_events: true
    write_event_info: false
    generated_events: 5030599755
    livetime: 1301940

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/preselection_CRY_onspill-LH_au"