#
# preselection_CRY_offspill-LH_as.yaml
#

process:
    file_list_path: "../input/filelists/nts.mu2e.CosmicCRYSignalAllOffSpillTriggered-LH.MDC2020as_best_v1_3_v06_03_00.100.txt"
    cutset_name: "SU2020a" 
    on_spill: false
    groups_to_toggle:
        Tracker : false
        CRV : false
        Momentum: false
    max_workers: 100 
    verbosity: 1 
    
postprocess:
    write_events: true
    write_event_info: false
    generated_events: 5030599755
    livetime: 1301940
    
output:
    out_path: "../output/results/preselection_CRY_offspill-LH_as"