#
# preselection_signal_onspill-LH_au
#

process:
    file_list_path: "../input/file_lists/nts.mu2e.CeEndpointOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.100.txt"
    on_spill: true
    cutset_name: "SU2020a" 
    groups_to_toggle:
        Tracker : false
        CRV : false
        Momentum: false
    max_workers: 100 
    verbosity: 1 
    
postprocess:
    write_events: true
    write_event_info: false
    generated_events: 400000
    veto: false

output:
    out_path: "../output/results/preselection_signal_onspill-LH_au"