# ===============================
# SU2020c_CRY_offspill-LH_aq.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aq_best_v1_3_v06_03_00.root"
    location: "tape"
    cutset_name: "SU2020c"

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 41100000000
    livetime: 10690000

output:
    out_path: "../output/results/SU2020c_CRY_onspill-LH_aq"