# ===============================
# SU2020c_CRY_offspill-LH_as.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOffSpillTriggered-LH.MDC2020as_best_v1_3_v06_03_00.root"
    cutset_name: "SU2020c"
    on_spill: false
    
postprocess:
    write_events: true
    write_event_info: true
    generated_events: 41100000000
    livetime: 10630000.0

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020c_CRY_offspill-LH_as"