# ===============================
# SU2020c_signal_onspill-LH_an.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020an_v06_01_01_best_v1_3.root"
    on_spill: true
    location: "tape"
    cutset_name: "SU2020c"
    max_workers: 50
    cuts_to_toggle:
        unvetoed: false

postprocess:
    write_events: false
    write_event_info: false

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020c_signal_onspill-LH_an"