# ===============================
# SU2020a_signal_onspill-LH_aw.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.root"
    cutset_name: "SU2020a"
    cuts_to_toggle:
        unvetoed: false

postprocess:
    write_events: false
    write_event_info: false
    generated_events: 4000000
    livetime: null

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020a_signal_onspill-LH_aw"