# ===============================
# SU2020d_CRY_onspill-LH_au.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.root"
    cutset_name: "SU2020d"
    max_workers: 100

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 4000000
    livetime: 10680000
    
output:
    out_path: "../output/results/SU2020d_CRY_onspill-LH_au"