# ===============================
# SU2020b_CRY_onspill-LH_au.yaml
# ===============================

process:
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.root"
    on_spill: true
    cutset_name: "SU2020b"

postprocess:
    write_events: true
    write_event_info: true

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020b_CRY_onspill-LH_au"