# ===============================
# SU2020c_signal-onspill_au.yaml
# ===============================

process:
    defname: "nts.mu2e.CeEndpointOnSpillTriggered.MDC2020au_best_v1_3_v06_03_00.root"
    on_spill: true
    location: "disk"
    cutset_name: "SU2020c"
    max_workers: 50
    cuts_to_toggle:
        unvetoed: false

postprocess:
    write_events: false
    write_event_info: false

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020c_signal_onspill-LH_au"