# ===============================
# SU2020b_CRY_onspill-LH_aw_test.yaml
# ===============================

process:
    file_name: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/files/nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.001202_00010066.root"
    # file_name: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.001202_00010066.root"
    # file_name: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.001202_00010066.root"
    #file_list_path: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/filelists/nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_perfect_v1_3_v06_06_00.10.txt"
    cutset_name: "SU2020b"
    use_remote: false

postprocess:
    write_events: true
    write_event_info: true
    generated_events: 500000000 # 50000000
    livetime: 130194.0 # 13019.4

output:
    out_path: "../output/results/SU2020b_CRY_onspill-LH_aw_test"