# ===============================
# SU2020a_CRY_offspill-LH_aw.yaml
# ===============================

process:
    # defname (str, opt): Dataset definition name. Defaults to None.
    # file_list_path (str, opt): Path to file list. Defaults to None.
    # file_name (str, opt): Single file to process. Defaults to None.
    # cutset_name (str, opt): Which cutset to use. Defaults to "SU2020a".
    # branches (dict or list, opt): EventNtuple branches to extract.
    # on_spill (bool, opt): Apply on-spill timing cuts. Defaults to False.
    # cuts_to_toggle (dict, opt): Cuts to enable/disable. Defaults to None.
    # use_remote (bool, opt): Use remote file access. Defaults to True.
    # location (str, opt): File location ("disk", etc.). Defaults to "disk".
    # max_workers (int, opt): Number of parallel workers. Defaults to 50.
    # verbosity (int, opt): Logging verbosity level. Defaults to 2.
    # use_processes (bool, opt): Use processes rather than threads. Defaults to True.
    defname: "nts.mu2e.CosmicCRYSignalAllOnSpillTriggered.MDC2020aw_best_v1_3_v06_05_00.root"
    on_spill: true
    max_workers: 50
    cutset_name: "SU2020a"

postprocess:
    # write_events (bool, opt): write filtered events. Defaults to False.
    # write_event_info (bool, opt): write filtered event info. Defaults to False.
    # generated_events (int, opt): Number of generated events. Defaults to 4e6.
    # veto (bool, opt): Whether running with CRV veto. Defaults to True.
    # wilson (bool, opt): Whether to use Wilson or Poisson for efficiency uncertainty. Defaults to True.
    # verbosity (int, opt): Printout level. Defaults to 1.
    write_events: true
    write_event_info: true

output:
    # Define a unique output path relative to script directory
    out_path: "../output/results/SU2020a_CRY_onspill-LH_aw"