# ============================================================================
# COSMIC PROCESSOR ANALYSIS CONFIGURATION
# ============================================================================
# This YAML file configures a cosmic-ray-induced background analysis 
# The configuration is divided into three main sections: 
# processor settings, postprocessing options, and output paths.
# 
# Naming: <cutset_name>_<dataset>.yaml
#

processor:
    # See src/core/process.py
    # Args:
    #     defname (str, opt): Dataset definition name. Defaults to None.
    #     file_list_path (str, opt): Path to file list. Defaults to None.
    #     file_name (str, opt): Single file to process. Defaults to None.
    #     cutset_name (str, opt): Which cutset to use. Defaults to "alpha".
    #     branches (dict or list, opt): EventNtuple branches to extract.
    #     on_spill (bool, opt): Apply on-spill timing cuts. Defaults to False.
    #     cuts_to_toggle (dict, opt): Cuts to enable/disable. Defaults to None.
    #     use_remote (bool, opt): Use remote file access. Defaults to True.
    #     location (str, opt): File location ("disk", etc.). Defaults to "disk".
    #     max_workers (int, opt): Number of parallel workers. Defaults to 50.
    #     verbosity (int, opt): Logging verbosity level. Defaults to 2.
    #     use_processes (bool, opt): Use processes rather than threads. Defaults to True.
    file_name: "/exp/mu2e/data/users/sgrant/mu2e-cosmic/data/nts.mu2e.CosmicCRYSignalAllOffSpillTriggered-LH.MDC2020as_best_v1_3_v06_03_00.001202_00050440.root"
    use_remote: false

postprocess:
    # info should be false when running with no veto or loose cuts
    info: true

output:
    # Define a unique output path
    out_path: "../out/results/test"